<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.17" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.17" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.17" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.61.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
	<PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
	<PackageReference Include="Blazored.SessionStorage" Version="2.4.0" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../FoodHub.Domain.Share/FoodHub.Domain.Share.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Extension\" />
		<Folder Include="Interfaces\" />
		<Folder Include="Service\" />
	</ItemGroup>
</Project>
